---
dependencies:
- name: "jenkins"
  repository: "https://charts.helm.sh/stable"
  version: "1.27.0"
- name: "exposecontroller"
  repository: "http://chartmuseum.jenkins-x.io"
  version: "2.3.95"
  alias: "jenkinsexpose"
- name: "exposecontroller"
  repository: "http://chartmuseum.jenkins-x.io"
  version: "2.3.95"
  alias: "jenkinscleanup"
- name: "jx"
  alias: "jenkinstokenjob"
  repository: "http://chartmuseum.jenkins-x.io"
  version: "1.3.965"
  condition: "jenkinstokenjob.enabled"
